### ISSUE TITLE
ImportError: cannot import name 'Session'

### ISSUE THREAD

**Issue by jkatsioloudes** [barnumbirr/coinmarketcap#36]
I have this error in python 3.6 and I believe is due to a parameter name change I read about here: https://github.com/kennethreitz/twitter-scraper/issues/15

Traceback (most recent call last):
  File "/<MY_PATH>/coin_market_cap.py", line 1, in <module>
    from coinmarketcap import Market
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coinmarketcap/__init__.py", line 10, in <module>
    from .core import Market
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/coinmarketcap/core.py", line 8, in <module>
    import requests_cache
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests_cache/__init__.py", line 28, in <module>
    from .core import(
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests_cache/core.py", line 14, in <module>
    from requests import Session as OriginalSession

**Comment by barnumbirr** [comment]
Hey @jkatsioloudes,

error actually comes from [requests-cache](https://github.com/reclosedev/requests-cache/blob/master/requests_cache/core.py#L14). Did you install the required dependencies from the requirements.txt file?

Cheers.

**Comment by jkatsioloudes** [comment]
Hey @barnumbirr,

I am using PyCharm to code so the import was made from there, thanks for letting me know, sorry if it is a stupid question but how can I do it?

**Comment by barnumbirr** [comment]
Hello again,

a simple

```bash
$ pip install -r /path/to/requirements.txt
```
 should do it.

Cheers.
