### ISSUE TITLE
Im numb

### ISSUE THREAD

**Issue by wardj1999** [barnumbirr/coinmarketcap#37]
So im calling
>>> from coinmarketcap import Market
>>> coinmarketcap = Market()
>>> coinmarketcap.ticker(start=0, limit=3, convert='EUR')

as stated in the manual you provided  and I have installed all the dependicies using PyCharm but every time I run it it just returns 

Traceback (most recent call last):
  File "C:/Users/J/PycharmProjects/Learning/coinmarketcap.py", line 1, in <module>
    from coinmarketcap import Market
  File "C:\Users\J\PycharmProjects\Learning\coinmarketcap.py", line 1, in <module>
    from coinmarketcap import Market
ImportError: cannot import name 'Market'

I'm pretty new to python but have coded in the past in other languages im just not understanding what im doing wrong.
I have requests installed and requests cache installed i tried restarting PyCharm to see if maybe they werent registering but still to no avail. The module is installed in my Pycharm directory and the class Market() does exist im just not sure what im doing wrong...

**Comment by wardj1999** [comment]
Nvm my file had the same name as the module so it was just calling from my coinmarketcap.py file and not the module lol i dont know how to close issues but if you could thatd be great :)
